### ISSUE TITLE
Remaining subjects with direct S3 URLs

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Talk-archiver#63]
Subject locations are slightly complicated because subject URLs are denormalised throughout the Ouroboros API responses. Some projects also use buckets other than `zooniverse-static` eg.
http://asteroidzoo.s3.amazonaws.com/CSS/703/2012/12Jun17/azoo/01_12JUN17_N26072_0001-91-scaled.png
https://mwp-development.s3.amazonaws.com/bubble_centred/large/GLM_327144%2B00917_mosaic_0.0947x0.0473_I24M1.jpg

_Originally posted by @eatyourgreens in https://github.com/zooniverse/Talk-archiver/issues/49#issuecomment-651939689_

**Comment by eatyourgreens** [comment]
c2979dff30e6618206cf7ffff52870335371bb23 adds another JSON file to each build. `/manifest/hosts.json` contains the hosts used by subject locations and the total number of subjects for each host.

eg. https://talk.floatingforests.org/manifest/hosts.json
```json
{"www.floatingforests.org":9313,"static.zooniverse.org":761}
```

**Comment by eatyourgreens** [comment]
After rebuilding all the sites in #55, only Asteroid Zoo and Milky Way Zoo are using custom S3 buckets.

**Comment by eatyourgreens** [comment]
Not checked yet: all the projects in #56.

**Comment by camallen** [comment]
> After rebuilding all the sites in #55, only Asteroid Zoo and Milky Way Zoo are using custom S3 buckets.

We have confirmed we don't own either of these s3 buckets. So they must be owned by the research team and it's up to them to leave them online for posterity. We don't have to rewrite these urls

**Comment by eatyourgreens** [comment]
The Galaxy Zoo Talk home page has a bunch of broken images that use S3 URLs. https://talk.galaxyzoo.org/recent/

**Comment by camallen** [comment]
The GZ images should be mostly fixed now - however some still remain broken as we can't differentiate between the static bucket images and the www.galaxyzoo.irg bucket images.

From slack, https://zooniverse.slack.com/archives/C0138Q1LVCL/p1597247248201900

Re GZ thumbnail URLs above, some images still don’t resolve via the thumbnailer due to a clashing of paths for static bucket and the www.galaxyzoo.org bucket, details in https://github.com/zooniverse/thumbnailer/pull/14#issuecomment-672949262

See bottom of this page for some missing thumbnail images, https://talk.galaxyzoo.org/collections/CGZS0002cc/

I think the best way forward to ensure we have all thumbnails working is to use the subject locations.thumbnail property instead of the standard image when we want to use thumbnails in the HMTL output for this project.

I believe all GZ subjects have the 3 location properties, standard, thumbnail, inverted e.g. https://talk.galaxyzoo.org/api/subjects/AGZ0007r51.json

those non-static URLs will just have to be served from our s3 buckets and we just keep paying for these (very small $$).

This means we will have to redo the GZ talk build / deploy again.

However i think we will have to do this to avoid the cert errors on some image URLs as well as we have to rewrite them to non virtual domain paths, https://zooniverse.slack.com/archives/C0138Q1LVCL/p1597152791175900?thread_ts=1597142302.166000&cid=C0138Q1LVCL

Thoughts?

**Comment by eatyourgreens** [comment]
857e47c14eabd41584d49a42dab9a882c1774410 adds a rule to ignore S3 URLs when deciding whether to use the thumbnail service.

**Comment by eatyourgreens** [comment]
d1855144ca447cbbc820a1752378d81f10b440cc rewrites old Galaxy Zoo subjects to use https://s3.amazonaws.com. You can see the results on the Recents page:
https://talk.galaxyzoo.org/recent/

and on this subject discussion:
https://talk.galaxyzoo.org/boards/BGZ0000005/discussions/DGZ0000kbk/

I think that discussion is still throwing a security warning in the browser because there's an image in a comment that uses `http://`. I don't think there's much we can do about those.

**Comment by camallen** [comment]
good one - so the only GZ image issue is some broken images that our thumbnailer can't render
e.g last third of these images - https://talk.galaxyzoo.org/collections/CGZS0002cc/

I think the best approach (outlined above) is to avoid using thumbnailer service for gz project as the images are distributed across buckets and we can't distinguish via subject metadata which is which. 

I believe we can switch to straight subject location thumbnails path on this project, perhaps adding more logic to https://github.com/zooniverse/Talk-archiver/blob/c4c877f08a54b823c56b42b75490c5042b442cfa/src/components/subjectImage.js#L26 ? 

One strategy could be to reflect is the subject has thumbnails and just use that - fail over to thumbnail service if not.
```
if (passThrough) {
 var src = url;
} else {
 var thumbnailSrc = subjectLocation(subject.location.thumbnail || subject.thumbnail);
 var src = thumbnailSrc ? thumbnailSrc : `https://thumbnails.zooniverse.org/150x150/${thumbnailPath.replace(staticRoot, '')}`
}```

**Comment by eatyourgreens** [comment]
I think https://github.com/zooniverse/Talk-archiver/commit/857e47c14eabd41584d49a42dab9a882c1774410 fixes the thumbnails. I'm not seeing broken thumbnails any more on the GZ Recents page. Compare with the screenshot in this comment: https://github.com/zooniverse/Talk-archiver/issues/56#issuecomment-672071194

**Comment by camallen** [comment]
Right - so https://github.com/zooniverse/Talk-archiver/commit/857e47c14eabd41584d49a42dab9a882c1774410 will use the standard image vs the thumbnail right - that's a good solution too. 

Can we rebuild this collection page for GZ to test the thumbnail issue? That page has images that the thumbnailer can't correctly process due to s3 bucket path uncertainty (static vs www.galaxyzoo.org).
 https://talk.galaxyzoo.org/collections/CGZS0002cc/

**Comment by eatyourgreens** [comment]
I think I see now. The thumbnailer can't resolve URLs that begin `https://www.galaxyzoo.org/`, like this subject, for example: https://talk.galaxyzoo.org/subjects/AGZ00078q9/

I think that needs changes similar to the changes that use `subject.location.previews[0][0]` for Chimp & See. https://github.com/zooniverse/Talk-archiver/pull/74

**Comment by camallen** [comment]
yes - exactly. I tried to outline the details in https://github.com/zooniverse/thumbnailer/pull/14#issuecomment-672938853 i probably should have included them here. 

Once we sort this out i think we're in the home stretches for GZ and other sites.

**Comment by eatyourgreens** [comment]
I think we can add `subject.location.thumbnail` as another possible value for `previewLocation` and also a rule to pass through URLs beginning with `https://ww.galaxyzoo.org`.
https://github.com/zooniverse/Talk-archiver/blob/33f3a876bfab77fa42e9c86a5ec3e0831ac21641/src/components/subjectImage.js#L17-L29

Development and deployment for these big projects is happening with the branch in #72. I should probably just merge it to master. It's been used to build everything listed in #56.

**Comment by camallen** [comment]
ok - great re the plan. Agree with the plan for merging the brances - the builds seems to be working well.

**Comment by eatyourgreens** [comment]
I've rebuilt all of Galaxy Zoo now with the changes from #77.

**Comment by eatyourgreens** [comment]
I've lost track of which domain resolves where: should these S3 domains be re-written to `www.galaxyzoo.org` so that we don't have any references to S3 in the GZ pages? At the moment, those locations will all be using `https://s3.amazonaws.com`.
https://github.com/zooniverse/Talk-archiver/blob/60d38582045b0a76d80c6a22630c8c4063cfb32a/src/helpers/subjectLocation.js#L30

**Comment by camallen** [comment]
I'm looking into modifying the static server to proxy the `www.galaxyzoo/subjects/*` host  & paths to the correct s3 bucket. If i can get this working then we can rewrite the bucket paths you have above to explicitly use our `www.galaxyzoo.org` domain instead of hard coding the s3 URLs, e.g. 
http://www.galaxyzoo.org.s3.amazonaws.com/subjects/decals/thumbnail/J211326.08%2B005811.6_thumbnail.jpeg
becomes (the latter is currently broken due to incorrect URL escaping on redirect)
https://www.galaxyzoo.org/subjects/decals/thumbnail/J211326.08%2B005811.6_thumbnail.jpeg

This is a good idea - if we can get this working, we can migrate the `www.galaxyzoo.org` bucket data to azure as well and update our nginx proxy to handle the s3 / azure target.

If i can't get this working then we will just use the hard coded s3 URLs, we'll just keep that data in s3 in perpetuity and move on.

**Comment by eatyourgreens** [comment]
#81 removes S3 URLs from Galaxy Zoo, so I think that only leaves the subjects in buckets that we don’t host: Asteroid Zoo and Milky Way Project.

**Comment by camallen** [comment]
this is all done - all Zooniverse controlled subjects use non s3 domain URLs.
